---
theme: jekyll-theme-cayman
title: Electronic Playground
description: Hamza Imran | Portfolio in Electronics & Automation — A personal showcase of my electronics and automation projects, including smart home systems, IoT devices, and embedded tech.
---
