theme: jekyll-theme-cayman
title: Hamza Imran | Portfolio in Electronics & Automation
description: A personal showcase of my electronics and automation projects, including smart home systems, IoT devices, and embedded tech.

